apiVersion: v1
kind: Service
metadata:
  name: dot-collector
  namespace: default
  labels:
    app: dot-collector
spec:
  selector:
    app: dot-collector
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP