apiVersion: v1
kind: Service
metadata:
  name: btc-collector
  namespace: btc-app
  labels:
    app: btc-collector
spec:
  selector:
    app: btc-collector
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP