apiVersion: v1
kind: Service
metadata:
  name: crypto-ingestor
  namespace: default
  labels:
    app: crypto-ingestor
spec:
  selector:
    app: crypto-ingestor
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP