apiVersion: v1
kind: Service
metadata:
  name: sol-collector
  namespace: sol-app
  labels:
    app: sol-collector
spec:
  selector:
    app: sol-collector
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP