apiVersion: v1
kind: Service
metadata:
  name: ada-collector
  namespace: default
  labels:
    app: ada-collector
spec:
  selector:
    app: ada-collector
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP