startServices: "s3"
debug: false
persistence:
  enabled: false # Save disk space, use ephemeral for now
service:
  type: NodePort
  nodePort: 30000 # Fixed port for easier access if needed
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
extraEnvVars:
  - name: EAGER_SERVICE_LOADING
    value: "1"
  - name: SERVICES
    value: "s3"
