apiVersion: v1
kind: Service
metadata:
  name: eth-collector
  namespace: default
  labels:
    app: eth-collector
spec:
  selector:
    app: eth-collector
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP