apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-frontend
  namespace: default
  labels:
    app: crypto-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-frontend
  template:
    metadata:
      labels:
        app: crypto-frontend
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsGroup: 2000
      containers:
        - name: crypto-frontend
          image: diegohnunes/crypto-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: DB_PATH
              value: "/data/crypto.db"
          volumeMounts:
            - name: shared-data
              mountPath: /data
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: crypto-shared-storage
